#!/usr/bin/env python

# Created on Tue Sep 8 20:45:18 2020
# Author: XiaoTao Wang

## Required modules

import argparse, sys, logging, eaglec, os

currentVersion = eaglec.__version__

def getargs():
    ## Construct an ArgumentParser object for command-line arguments
    parser = argparse.ArgumentParser(description='''Predict structural variants (SVs) from multi-resolution
                                     Hi-C contact maps using EagleC2. The workflow performs genome-wide
                                     candidate scanning with a stage-1 FCN model, SV classification with
                                     stage-2 ensemble models, removal of redundant predictions across resolutions,
                                     and recursive fine-mapping of SV coordinates at higher resolutions.''',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    
    # Version
    parser.add_argument('-v', '--version', action='version',
                        version=' '.join(['%(prog)s',currentVersion]),
                        help='Print version number and exit.')

    parser.add_argument('--mcool', required=True, help='''Path to an input .mcool file containing Hi-C contact
                        matrices at multiple resolutions.''')
    parser.add_argument('-O', '--output-prefix', required=True, help='''Prefix of the output file names''')
    parser.add_argument('--scan-resolutions', default='5000,10000,25000',
                        help='Comma-separated resolutions for FCN scanning and SV prediction.')
    parser.add_argument('--refine-resolutions', default='1000,2000,5000,10000,25000',
                        help='Comma-separated resolutions for SV refinement (must include scan resolutions).')
    parser.add_argument('--balance-type', default='ICE', choices=['ICE', 'CNV', 'Raw'],
                        help = '''Normalization method used when reading Hi-C matrices: ICE -> "weight",
                        CNV -> "sweight", Raw -> unbalanced counts.''')
    parser.add_argument('--model-path', default='EagleC2-models',
                        help='''Path to the folder containing pretrained stage-2 ensemble models.''')
    parser.add_argument('-g', '--genome', default='hg38', choices = ['hg38', 'hg19', 'chm13', 'other'],
                       help='''Reference genome used for loading gap/blacklist annotations. If "other"
                       is specified, no gap/blacklist annotation will be loaded.''')
    parser.add_argument('-C', '--chroms', nargs = '*', default = ['#', 'X'],
                        help = '''List of chromosome labels to include. "#" represents all numerically
                        labeled chromosomes. Additional chromosomes such as X or Y can be listed explicitly.
                        Using "--chroms" with zero arguments includes all chromosomes in the mcool file.''')
    parser.add_argument('--candidate-cutoff', default=0.25, type=float, help='''Probability cutoff used in
                        stage-1 FCN genome-wide scanning to select candidate SV loci. Range: [0, 1].''')
    parser.add_argument('--sv-cutoff', default=0.2, type=float, help='''Probability cutoff used in stage-2
                        SV prediction and as the baseline support threshold during recursive fine-mapping.
                        Range: [0, 1].''')
    parser.add_argument('--tile-size', default=2048, type=int, help='''Tile size used for genome-wide
                        stage-1 FCN scanning.''')
    parser.add_argument('-p', '--nproc', default=8, type=int,
                        help='Maximum number of CPU processes used for expected-value calculation and' \
                        'related preprocessing.')
    parser.add_argument('--cpu', action='store_true',
                        help='''Force the program to run entirely on CPU, even if a GPU is available.''')

    ## Parse the command-line arguments
    commands = sys.argv[1:]
    if not commands:
        commands.append('-h')
    args = parser.parse_args(commands)
    
    return args, commands

def parse_resolutions(res_str):
    return sorted([int(r) for r in res_str.split(',')])

def run():

    # Parse Arguments
    args, commands = getargs()
    # Improve the performance if you don't want to run it
    if commands[0] not in ['-h', '-v', '--help', '--version']:
        ## Root Logger Configuration
        logger = logging.getLogger()
        logger.setLevel(logging.DEBUG)
        console = logging.StreamHandler()
        logfil = '{0}.log'.format(args.output_prefix)
        filehandler = logging.FileHandler(logfil)
        # Set level for Handlers
        console.setLevel(logging.INFO)
        filehandler.setLevel(logging.INFO)
        # Customizing Formatter
        formatter = logging.Formatter(fmt = '%(name)-25s %(levelname)-7s @ %(asctime)s: %(message)s',
                                      datefmt = '%m/%d/%y %H:%M:%S')
        
        ## Unified Formatter
        console.setFormatter(formatter)
        filehandler.setFormatter(formatter)
        # Add Handlers
        logger.addHandler(console)
        logger.addHandler(filehandler)
        
        ## Logging for argument setting
        arglist = [
            '# ARGUMENT LIST:',
            '# Path to mcool = {0}'.format(args.mcool),
            '# Scan Resolutions = {0}'.format(args.scan_resolutions),
            '# Refine Resolutions = {0}'.format(args.refine_resolutions),
            '# Balance Type = {0}'.format(args.balance_type),
            '# Path to stage-2 models = {0}'.format(args.model_path),
            '# Reference Genome = {0}'.format(args.genome),
            '# Included Chromosomes = {0}'.format(args.chroms),
            '# Candidate Cutoff = {0}'.format(args.candidate_cutoff),
            '# SV Cutoff = {0}'.format(args.sv_cutoff),
            '# Tile Size = {0}'.format(args.tile_size),
            '# Number of Allocated Processes = {0}'.format(args.nproc),
            '# Output File Prefix = {0}'.format(args.output_prefix),
            '# CPU Only = {0}'.format(args.cpu)
        ]
        argtxt = '\n'.join(arglist)
        logger.info('\n' + argtxt)

        import tensorflow as tf

        if args.cpu:
            # Force TensorFlow to use CPU only
            tf.config.set_visible_devices([], 'GPU')
            logger.info('Running on CPU only.')
            #logger.info('Visible devices: {0}'.format(tf.config.get_visible_devices('GPU')))

        import cooler, time, tempfile, joblib
        from eaglec.utilities import calculate_expected_intra, calculate_expected_intra, load_gap
        from eaglec.searchCandidates import collect_candidate_patches, iter_cooler_scan_candidates
        from eaglec.predictCore import load_ensemble_models, load_fcn_model, predict, refine_predictions

        # read resolutions
        scan_resolutions = parse_resolutions(args.scan_resolutions)
        refine_resolutions = parse_resolutions(args.refine_resolutions)
        
        if not set(scan_resolutions).issubset(set(refine_resolutions)):
            raise ValueError('scan_resolutions must be a subset of refine_resolutions.')

        clr = cooler.Cooler('{0}::resolutions/{1}'.format(args.mcool, scan_resolutions[0]))
        # read chromosomes
        chroms = []
        for c in clr.chromnames:
            chromlabel = c.lstrip('chr')
            if (not args.chroms) or (chromlabel.isdigit() and '#' in args.chroms) or (chromlabel in args.chroms):
                chroms.append(c)
        
        # cache folder
        cache_root = os.path.abspath(os.path.expanduser('.eaglec2'))
        if not os.path.exists(cache_root):
            os.mkdir(cache_root)

        tl = time.strftime('%Y%m%d%H%M%S', time.localtime(time.time()))
        cache_folder = tempfile.mkdtemp(**{'suffix':tl, 'dir':cache_root})

        # valid bins
        if args.balance_type == 'CNV':
            balance = 'sweight'
        elif args.balance_type == 'ICE':
            balance = 'weight'
        else:
            balance = False
        
        logger.info('Cache folder: {0}'.format(cache_folder))
        
        # expected values
        expected_values_intra = {}
        expected_values_inter = {}
        logger.info('Calculating the expected values ...')
        for res in refine_resolutions:
            logger.info('  Resolution {0}'.format(res))
            max_bins = max(200, 2000000//res)
            clr = cooler.Cooler('{0}::resolutions/{1}'.format(args.mcool, res))
            expected_values_intra[res] = calculate_expected(clr, chroms, balance, max_bins, nproc=args.nproc)
            expected_values_inter[res] = calculate_expected_inter(clr, chroms, balance, nproc=args.nproc)
        joblib.dump(expected_values_intra, os.path.join(cache_folder, 'expected_values_intra.pkl'))
        joblib.dump(expected_values_inter, os.path.join(cache_folder, 'expected_values_inter.pkl'))

        logger.info('Done')

        logger.info('Scanning genome using FCN ...')
        fcn_model = load_fcn_model()
        candidates, count = iter_cooler_scan_candidates(
            cool_path=mcool_path,
            resolutions=scan_resolutions,
            chroms=chroms,
            expected_intra=expected_values_intra,
            expected_inter=expected_values_inter,
            balance=balance,
            base_fcn=fcn_model,
            tile_size=tile_size,
            cutoff=candidate_cutoff
        )
        logger.info('Totally detected {0} candidates'.format(count))

        logger.info('Extracting candidate patches ...')
        patch_count = collect_candidate_patches(
            cool_path=args.mcool,
            candidates=candidates,
            expected_intra=expected_values_intra,
            expected_inter=expected_values_inter,
            out_dir=cache_folder,
            balance=balance
        )
        logger.info('Totally collected {0} patches'.format(patch_count))
        
        logger.info('Loading stage-2 models ...')
        models = load_ensemble_models(args.model_path)
        logger.info('Done')
        # load gap regions
        gaps = {}
        for res in refine_resolutions:
            clr = cooler.Cooler('{0}::resolutions/{1}'.format(args.mcool, res))
            gaps[res] = load_gap(clr, chroms, ref_genome=args.genome, balance=balance)

        logger.info('Predicting SVs ...')
        original_predictions = predict(
            cache_folder,
            models,
            gaps,
            prob_cutoff=args.sv_cutoff
        )

        logger.info('Done')

        logger.info('Refining SV coordinates ...')
        SVs = refine_predictions(
            original_predictions,
            refine_resolutions,
            models,
            args.mcool,
            balance,
            exp=expected_values,
            ref_gaps=gaps,
            cache_folder=cache_folder,
            baseline_prob=args.sv_cutoff
        )
        logger.info('Done')

        logger.info('SV calls written to {0}.SV_calls.txt'.format(args.output_prefix))
        with open('{0}.SV_calls.txt'.format(args.output_prefix), 'w') as out:
            out.write('\t'.join(['chrom1', 'pos1', 'chrom2', 'pos2', '++', '+-', '-+', '--', '++/--', '+-/-+',
                                 'original resolution', 'fine-mapped resolution', 'info'])+'\n')
            for line in SVs:
                c1, p1, c2, p2, prob1, prob2, prob3, prob4, prob5, prob6, res1, res2, info_g, info_s = line
                out.write('{0}\t{1}\t{2}\t{3}\t{4:.4g}\t{5:.4g}\t{6:.4g}\t{7:.4g}\t{8:.4g}\t{9:.4g}\t{10}\t{11}\t{12},{13}\n'.format(c1, p1, c2, p2, prob1, prob2, prob3, prob4, prob5, prob6, res1, res2, info_g, info_s))

        logger.info('Done')


if __name__ == '__main__':
    run()
